README.md
| Tests pass?   | ❌
| Fixed issues  |
=> Update SwiftMailer's link

bash.exe.stackdump, tests/BaseMailerTest.php, tests/config.php
=> Cleanup, improve test

.gitignore, README.md, composer.json, psalm.xml
| New feature?  | ✔️/❌
| Fixed issues  |
=> Adopt Psalm

.github/workflows/bc.yml_, .github/workflows/build.yml, .github/workflows/mutation.yml, .github/workflows/static.yml, .scrutinizer.yml, README.md, composer.json, phpunit.xml.dist, psalm.xml, src/BaseMailer.php, src/BaseMessage.php, src/Composer.php, src/FileMailer.php, src/MailerInterface.php, src/MessageFactory.php, src/MessageFactoryInterface.php, src/MessageInterface.php, src/Template.php, tests/BaseMailerTest.php, tests/ComposerTest.php
=> Update dev dependencies, pipelines, scrutinizer, clean code.

.gitignore, src/FileMailer.php
| Is bugfix?    | ✔️/❌
| Fixed issues  |
=> Fix static analysis

src/Mailer.php, src/MailerInterface.php, src/MessageBodyRenderer.php, tests/MessageBodyRendererTest.php
=> Add ability to pass parameters in layouts

src/Mailer.php, src/MessageBodyRenderer.php, tests/MailerTest.php
=> Add immutable setters to Mailer class

src/Mailer.php, src/MailerInterface.php, src/MessageBodyRenderer.php, src/MessageBodyTemplate.php, tests/MailerTest.php, tests/MessageBodyRendererTest.php, tests/MessageBodyTemplateTest.php, tests/TestCase.php
| Fixed issues  | https://github.com/yiisoft/mailer-swiftmailer/issues/33
=> Add MessageBodyTemplate

README.md, src/MessageBodyRenderer.php, tests/FileMailerTest.php, tests/MailerTest.php, tests/TestCase.php
| Readability fix  | according to https://github.com/yiisoft/docs/issues/155, chain calls must be put on separate lines.
=> Separate chain calls

CHANGELOG.md, README.md, composer.json, src/Mailer.php, src/MailerInterface.php, src/MessageBodyRenderer.php, tests/MailerTest.php, tests/MessageBodyRendererTest.php
Merge after https://github.com/yiisoft/view/pull/199
=> Add `withLocale` to localize render view file

.github/workflows/bc.yml, CHANGELOG.md, composer.json, psalm.xml
=> Add support of `yiisoft/view` of version `^8.0`

.styleci.yml, tests/TestCase.php
=> Update StyleCI config

.github/workflows/bc.yml, .github/workflows/build.yml, .github/workflows/composer-require-checker.yml, .github/workflows/mutation.yml, .github/workflows/rector.yml, .github/workflows/static.yml, .gitignore, CHANGELOG.md, README.md, composer.json, phpunit.xml.dist, tests/Event/AfterSendTest.php, tests/Event/BeforeSendTest.php, tests/FileMailerTest.php, tests/MailerTest.php, tests/MessageBodyRendererTest.php, tests/MessageBodyTemplateTest.php, tests/TestCase.php
=> Raise minimal PHP version to `^8.1`

CHANGELOG.md, composer.json, src/MessageFactory.php, src/MessageInterface.php, tests/MessageFactoryTest.php
=> Allow to set default "from" value in `MessageFactory`

README.md
=> Remove scrutinizer badge

CHANGELOG.md, src/Mailer.php, src/MailerInterface.php, src/Message.php, src/MessageInterface.php, src/MultipleSendResult.php, src/SendResults.php, tests/MailerTest.php, tests/MessageTest.php, tests/TestCase.php
=> Refactor `MailerInterface::sendMultiple()`

CHANGELOG.md, src/Message.php, src/MessageInterface.php, src/Priority.php, tests/MessageTest.php
=> Add `Priority` enumeration

CHANGELOG.md, composer-require-checker.json, composer.json, src/FileMailer.php, src/Mailer.php, tests/FileMailerTest.php
=> Make `psr/event-dispatcher` dependency optional

CHANGELOG.md, src/MessageBodyRenderer.php, src/MessageBodyTemplate.php, tests/MailerTest.php, tests/MessageBodyRendererTest.php, tests/MessageBodyTemplateTest.php, tests/TestCase.php
=> Refactor `MessageBodyTemplate`

CHANGELOG.md, composer.json
=> Add `yiisoft/view` of version `^11` support

CHANGELOG.md, src/BaseMailer.php, src/Event/AfterSend.php, src/Event/BeforeSend.php, src/File.php, src/FileMailer.php, src/MailerInterface.php, tests/BaseMailerTest.php, tests/Event/AfterSendTest.php, tests/Event/BeforeSendTest.php, tests/Support/DummyMailer.php, tests/TestAsset/DummyMailer.php, tests/TestCase.php
=> Rename `Mailer` to `BaseMailer` + Refactoring + Improve tests

CHANGELOG.md, composer.json, config/di.php, config/params.php, src/FileMailer.php, tests/BaseMailerTest.php, tests/ConfigTest.php, tests/FileMailerTest.php, tests/FileTest.php, tests/MessageSettingsTest.php, tests/MessageTest.php, tests/NullMailerTest.php, tests/StubMailerTest.php
=> Add `FileMailer` configuration

CHANGELOG.md, src/Message.php, src/MessageInterface.php
=> Change result type of `MessageInterface::with*` methods from `self` to `static`

CHANGELOG.md, README.md, composer.json, phpunit.xml.dist, psalm.xml, src/BaseMailer.php, src/Event/AfterSend.php, src/Event/BeforeSend.php, src/File.php, src/FileMailer.php, src/MailerInterface.php, src/Message.php, src/MessageInterface.php, src/MessageSettings.php, src/NullMailer.php, src/Priority.php, src/SendResults.php, src/StubMailer.php
=> Enable `findUnusedCode` + Improve readme

CHANGELOG.md, src/HtmlToTextBodyConverter.php, src/MessageSettings.php, tests/HtmlToTextBodyConverterTest.php, tests/MessageSettingsTest.php
=> Add `HtmlToTextBodyConverter`

README.md
=> Remove Yii Mailer View from readme
